/**
 * action 类型常量
 */

// 正在上映相关类型常量
export const FETCH_THEATERS_REQUEST = 'FETCH_THEATERS_REQUEST';
export const FETCH_THEATERS_FAILURE = 'FETCH_THEATERS_FAILURE';
export const FETCH_THEATERS_SUCCESS = 'FETCH_THEATERS_SUCCESS';

// 高分榜单相关类型常量
export const FETCH_TOP250_REQUEST = 'FETCH_TOP250_REQUEST';
export const FETCH_TOP250_FAILURE = 'FETCH_TOP250_FAILURE';
export const FETCH_TOP250_SUCCESS = 'FETCH_TOP250_SUCCESS';

// 电影搜索相关类型常量
export const KEYWORD_CHANGE = 'KEYWORD_CHANGE';
export const FETCH_SEARCH_REQUEST = 'FETCH_SEARCH_REQUEST';
export const FETCH_SEARCH_FAILURE = 'FETCH_SEARCH_FAILURE';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';

// 我的收藏相关类型常量
export const TOGGLE_FAVORITE = 'TOGGLE_FAVORITE';